CC=g++
CXXFLAGS=-g -std=c++11 -Wall -pedantic -D_GNU_SOURCE -Wno-format -Wno-long-long -I.

LDFLAGS=

MAKEDEPEND=${CC} -MM
PROGRAM=test_berencoder

OBJS = ${PROGRAM}.o asn1\ber\encoder.o asn1\ber\tag.o string\buffer.o

DEPS:= ${OBJS:%.o=%.d}

all: $(PROGRAM)

${PROGRAM}: ${OBJS}
	${CC} ${LDFLAGS} ${OBJS} ${LIBS} -o $@

clean:
	del ${PROGRAM}.exe ${OBJS} ${DEPS}

${OBJS} ${DEPS} ${PROGRAM} : Makefile.${PROGRAM}_win

.PHONY : all clean

%.d : %.cpp
	${MAKEDEPEND} ${CXXFLAGS} $< -MT ${@:%.d=%.o} > $@

%.o : %.cpp
	${CC} ${CXXFLAGS} -c -o $@ $<

-include ${DEPS}
